name: outlier_detection
channels:
  - defaults
dependencies:
  - python=3.7
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - keras
  - tensorflow-gpu
  - notebook
